### ISSUE TITLE
Bug Report: Rest client error: Error:     No response from Pub API call.    Search type: "PACKAGE".    Details: "Package name: dart:convert".

### ISSUE THREAD

**Issue by genglei01** [jeroen-meijer/pubspec-assist#12]
# Bug Report

## Steps to Reproduce

1. ...
2. ...
3. ...

## Exception Info

**Type:** `object`

**Name:** `Error`

**Message:** `Rest client error: Error: 
    No response from Pub API call.

    Search type: "PACKAGE".

    Details: "Package name: dart:convert".`

**Stack:**

```
Error: Rest client error: Error: 
    No response from Pub API call.

    Search type: "PACKAGE".

    Details: "Package name: dart:convert".
	at Object.getRestApiError (/Users/leogeng/.vscode-insiders/extensions/jeroen-meijer.pubspec-assist-0.3.5/out/model/pubError.js:68:16)
	at PubAPI.<anonymous> (/Users/leogeng/.vscode-insiders/extensions/jeroen-meijer.pubspec-assist-0.3.5/out/model/pubApi.js:118:34)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/leogeng/.vscode-insiders/extensions/jeroen-meijer.pubspec-assist-0.3.5/out/model/pubApi.js:4:58)
	at <anonymous>
```

**Comment by jeroen-meijer** [comment]
Hi there,

Thanks for the bug report.
However, I believe this is an error on the client-side and is not a result of a bug in the extension.

Also, I noticed that you were trying to install `dart:convert`, which is not a package you should install from Pub but is instead already present. Just import it using `import 'dart:convert';`

Closing.
Best regards.
