### ISSUE TITLE
Bug Report: Rest client error: Error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by burhanevive** [jeroen-meijer/pubspec-assist#23]
# Bug Report

## Steps to Reproduce

1. ...
2. ...
3. ...

## Exception Info

**Type:** `object`

**Name:** `Error`

**Message:** `Rest client error: Error: unable to get local issuer certificate`

**Stack:**

```
Error: Rest client error: Error: unable to get local issuer certificate
	at Object.getRestApiError (/Users/burhanuddin/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.6/out/model/pubError.js:68:16)
	at PubAPI.<anonymous> (/Users/burhanuddin/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.6/out/model/pubApi.js:67:34)
	at Generator.throw (<anonymous>)
	at rejected (/Users/burhanuddin/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.6/out/model/pubApi.js:5:65)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by jeroen-meijer** [comment]
Hi there,

Unfortunately I don’t know anything about this error. Please either add more context and information about the problem in your issue, or close it.

Thank you.

Regards.

**Comment by jeroen-meijer** [comment]
Not enough information provided.

Closing. Feel free to reopen.
