### ISSUE TITLE
Bug Report: Rest client error: Error: socket hang up

### ISSUE THREAD

**Issue by felixyin** [jeroen-meijer/pubspec-assist#3]
# Bug Report

## Steps to Reproduce

1. ...
2. ...
3. ...

## Exception Info

**Type:** `object`

**Name:** `Error`

**Message:** `Rest client error: Error: socket hang up`

**Stack:**

```
Error: Rest client error: Error: socket hang up
	at PubAPI.<anonymous> (/Users/fy/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.0/out/model/pubApi.js:66:23)
	at Generator.throw (<anonymous>)
	at rejected (/Users/fy/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.0/out/model/pubApi.js:5:65)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jeroen-meijer** [comment]
Hey there,

Thanks for your error report. This is actually not Pubspec Assist's fault but either Dart pub's API not responding in time or your internet connection may have been unstable at the time.

Eitherway, now I know what the error looks like, I can catch it so you'll see an appropriate message in the future.

Closing this.

Thanks again.

**Comment by jeroen-meijer** [comment]
This issue should be fixed in the new version.
Please open a new issue if you encounter this error again.
