### ISSUE TITLE
Bug Report: Rest client error: Error: connect ECONNREFUSED 172.217.194.121:443

### ISSUE THREAD

**Issue by tyokusuma** [jeroen-meijer/pubspec-assist#30]
# Bug Report

## Steps to Reproduce

1. ...
2. ...
3. ...

## Exception Info

**Type:** `object`

**Name:** `Error`

**Message:** `Rest client error: Error: connect ECONNREFUSED 172.217.194.121:443`

**Stack:**

```
Error: Rest client error: Error: connect ECONNREFUSED 172.217.194.121:443
	at Object.getRestApiError (/Users/tyokusuma27/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.6/out/model/pubError.js:68:16)
	at PubAPI.<anonymous> (/Users/tyokusuma27/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.6/out/model/pubApi.js:118:34)
	at Generator.throw (<anonymous>)
	at rejected (/Users/tyokusuma27/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.6/out/model/pubApi.js:5:65)
	at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by jeroen-meijer** [comment]
Hi there,

Unfortunately I don’t know anything about this error. Please either add more context and information about the problem in your issue, or close it.

Thank you.

Regards.

**Comment by JoshKisb** [comment]
faced same error

**Comment by jeroen-meijer** [comment]
Not enough information provided.

Closing. Feel free to reopen.
