### ISSUE TITLE
Bug Report: Rest client error: Error: connect ETIMEDOUT 216.58.203.19:443

### ISSUE THREAD

**Issue by a407184508** [jeroen-meijer/pubspec-assist#4]
# Bug Report

## Steps to Reproduce

1. ...
2. ...
3. ...

## Exception Info

**Type:** `object`

**Name:** `Error`

**Message:** `Rest client error: Error: connect ETIMEDOUT 216.58.203.19:443`

**Stack:**

```
Error: Rest client error: Error: connect ETIMEDOUT 216.58.203.19:443
    at PubAPI.<anonymous> (/Users/js/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.2/out/model/pubApi.js:66:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/js/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.2/out/model/pubApi.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jeroen-meijer** [comment]
(See #5)
