### ISSUE TITLE
Bug Report: Rest client error: Error: connect ETIMEDOUT 172.217.25.19:443

### ISSUE THREAD

**Issue by a407184508** [jeroen-meijer/pubspec-assist#5]
# Bug Report

## Steps to Reproduce

1. ...
2. ...
3. ...

## Exception Info

**Type:** `object`

**Name:** `Error`

**Message:** `Rest client error: Error: connect ETIMEDOUT 172.217.25.19:443`

**Stack:**

```
Error: Rest client error: Error: connect ETIMEDOUT 172.217.25.19:443
    at PubAPI.<anonymous> (/Users/js/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.2/out/model/pubApi.js:66:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/js/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.2/out/model/pubApi.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jeroen-meijer** [comment]
Hi there.

Unfortunately, this seems to be a bug I cannot fix, as it looks like this error is caused by either an unstable internet connection or a hiccup in the Dart API.
I'll push an update soon that explains this to the user.

Thanks for the report.

(I've closed the duplicatie issue.)
