### ISSUE TITLE
Bug Report: Expected YAML collection at dependencies. Remaining path: postgres

### ISSUE THREAD

**Issue by rodrigorahman** [jeroen-meijer/pubspec-assist#50]
# Bug Report

## Steps to Reproduce

1. ...
2. ...
3. ...

## Exception Info

**Type:** `object`

**Name:** `Error`

**Message:** `Expected YAML collection at dependencies. Remaining path: postgres`

**Stack:**

```
Error: Expected YAML collection at dependencies. Remaining path: postgres
	at YAMLMap.setIn (/Users/rodrigorahman/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/node_modules/yaml/dist/resolveSeq-4a68b39b.js:112:178)
	at Document.setIn (/Users/rodrigorahman/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/node_modules/yaml/dist/Document-2cf6b08c.js:574:21)
	at addDependencyByObject (/Users/rodrigorahman/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/out/functions/addDependency.js:193:16)
	at Object.<anonymous> (/Users/rodrigorahman/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/out/functions/addDependency.js:78:37)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/rodrigorahman/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/out/functions/addDependency.js:5:58)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by jeroen-meijer** [comment]
Hi, please open a new issue with more info and steps to reproduce.

Thanks. Closing this.
