### ISSUE TITLE
Bug Report: Expected YAML collection at dependencies. Remaining path: jaguar

### ISSUE THREAD

**Issue by unipenlabs** [jeroen-meijer/pubspec-assist#51]
# Bug Report

## Steps to Reproduce

1. ...
2. ...
3. ...

## Exception Info

**Type:** `object`

**Name:** `Error`

**Message:** `Expected YAML collection at dependencies. Remaining path: jaguar`

**Stack:**

```
Error: Expected YAML collection at dependencies. Remaining path: jaguar
	at YAMLMap.setIn (/Users/vasil/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/node_modules/yaml/dist/resolveSeq-4a68b39b.js:112:178)
	at Document.setIn (/Users/vasil/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/node_modules/yaml/dist/Document-2cf6b08c.js:574:21)
	at addDependencyByObject (/Users/vasil/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/out/functions/addDependency.js:193:16)
	at Object.<anonymous> (/Users/vasil/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/out/functions/addDependency.js:78:37)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/vasil/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/out/functions/addDependency.js:5:58)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by LeonDWong** [comment]
Same bug here, can anyone help?@jeroen-meijer
