### ISSUE TITLE
Bug Report: Rest client error: Error: connect ETIMEDOUT 172.217.25.19:443

### ISSUE THREAD

**Issue by yinLiangDream** [jeroen-meijer/pubspec-assist#6]
# Bug Report

## Steps to Reproduce

1. ...
2. ...
3. ...

## Exception Info

**Type:** `object`

**Name:** `Error`

**Message:** `Rest client error: Error: connect ETIMEDOUT 172.217.25.19:443`

**Stack:**

```
Error: Rest client error: Error: connect ETIMEDOUT 172.217.25.19:443
    at PubAPI.<anonymous> (/Users/Berry/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.2/out/model/pubApi.js:115:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/Berry/.vscode/extensions/jeroen-meijer.pubspec-assist-0.3.2/out/model/pubApi.js:5:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by jeroen-meijer** [comment]
This issue fixed in the new version.
Thanks again for the report.
Closing.
