### ISSUE TITLE
Bug Report: Expected YAML collection at dev_dependencies. Remaining path: http_auth

### ISSUE THREAD

**Issue by LeonDWong** [jeroen-meijer/pubspec-assist#71]
# Bug Report

## Steps to Reproduce

1. Creating a new empty *pubspec.yaml* file
2. Using pubspec-assist to add 'http-auth' package

## Exception Info

```
Error: Expected YAML collection at dev_dependencies. Remaining path: http_auth
    at YAMLMap.setIn (/Users/XXXXXX/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/node_modules/yaml/dist/resolveSeq-4a68b39b.js:112:178)
    at Document.setIn (/Users/XXXXXX/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/node_modules/yaml/dist/Document-2cf6b08c.js:574:21)
    at addDependencyByObject (/Users/XXXXXX/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/out/functions/addDependency.js:193:16)
    at Object.<anonymous> (/Users/XXXXXX/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/out/functions/addDependency.js:78:37)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/XXXXXX/.vscode/extensions/jeroen-meijer.pubspec-assist-2.0.0/out/functions/addDependency.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by LeonDWong** [comment]
#56
